
services:
  react-app1:
    container_name: react-app1
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:7000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./src:/app/src 
    stdin_open: true
    tty: true
    networks:
      - react-app
  
  react-app2:
    container_name: react-app2
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7002:7000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./src:/app/src 
    stdin_open: true
    tty: true
    networks:
      - react-app
      
  react-app3:
    container_name: react-app3
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7003:7000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./src:/app/src 
    stdin_open: true
    tty: true
    networks:
      - react-app

  nginx:  
    image: nginx:alpine 
    container_name: react-nginx
    restart: unless-stopped    
    ports:                      
      - 7000:7000
    volumes:
      - .:/app
      - /app/node_modules
      - ./src:/app/src 
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - react-app 

networks:
  react-app:
    driver: bridge