version: "3.7"
services:
  sample5:
    build:
      context: ./
      dockerfile: Dockerfile
    image: request-form
    container_name: sample5
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./:/var/www
    networks:
      - network5
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1
      DB_PORT: 3306
      DB_DATABASE: backend2
      DB_USERNAME: smct
      DB_PASSWORD: smct  # Ensure this matches your DB password 


  nginx-server:
    image: nginx:alpine
    container_name: backend-nginx
    restart: unless-stopped
    ports:
      - 7005:7005
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network5

networks:
  network5:
    driver: bridge

volumes:
  mysql_data5:  # Named volume for MySQL data
